{{- if or .Values.auth.apiKeys .Values.auth.apiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "banditdb.fullname" . }}-auth
  labels:
    {{- include "banditdb.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.auth.apiKeys }}
  BANDITDB_API_KEYS: {{ .Values.auth.apiKeys | quote }}
  {{- end }}
  {{- if .Values.auth.apiKey }}
  BANDITDB_API_KEY: {{ .Values.auth.apiKey | quote }}
  {{- end }}
{{- end }}
