#!/usr/bin/env bash
# Turn a generic appliance into one customer's instance. Runs once, on first
# boot, via banditdb-firstboot.service.
#
# Input comes from /etc/banditdb/customer.conf, which the launch script writes
# (Lightsail user-data). Everything customer-specific is generated here rather
# than baked into the image, so that N instances from one snapshot are N
# genuinely separate databases.
#
# Deliberately does NOT obtain a TLS certificate: that requires DNS to already
# resolve to this instance, which cannot be true before the instance exists.
# Run banditdb-enable-tls once the record is live.
set -euo pipefail

CONF_DIR=/etc/banditdb
DATA_DIR=/var/lib/banditdb
ENV_FILE="$CONF_DIR/banditdb.env"
CRED_FILE="$CONF_DIR/credentials.txt"

log() { printf '[firstboot] %s\n' "$*"; }

# ── SSH host keys, before anything else ──────────────────────────────────────
# generalize.sh deletes these so instances do not share one SSH identity. The
# primary mechanism that recreates them is an ExecStartPre hook on ssh.service,
# which cannot race. This is a backstop only — it runs after cloud-init, so by
# the time it executes sshd has normally sorted itself out. Kept because it costs
# nothing and repairs an instance that somehow came up without keys.
if ! compgen -G '/etc/ssh/ssh_host_*_key' >/dev/null; then
  log "no ssh host keys — generating"
  ssh-keygen -A
  # Clear any failure state from sshd having already died, then restart whichever
  # unit this release uses (socket-activated on 22.10+, plain service before).
  systemctl reset-failed ssh.socket ssh.service 2>/dev/null || true
  systemctl restart ssh.socket 2>/dev/null || systemctl restart ssh 2>/dev/null || true
  log "ssh host keys generated"
fi

if [[ -f "$ENV_FILE" ]]; then
  log "already provisioned; nothing to do"
  exit 0
fi

# ── Inputs, with defaults so a bare launch still produces a working box ───────
CUSTOMER_ID=""; SERVER_NAME=""; PLAN_TIER="starter"
REWARD_TTL_SECS=86400; MAX_PENDING=100000; RATE_LIMIT=1000; CORS_ORIGINS=""
# shellcheck disable=SC1091
[[ -f "$CONF_DIR/customer.conf" ]] && . "$CONF_DIR/customer.conf"

if [[ ! -f "$CONF_DIR/customer.conf" ]]; then
  # Almost always means this unit ran before cloud-init executed the user-data
  # script that writes customer.conf. The instance still comes up and serves,
  # but anonymously — worth shouting about rather than logging in passing.
  log "WARNING: $CONF_DIR/customer.conf not found."
  log "WARNING: falling back to defaults. If you passed a launch script, this"
  log "WARNING: unit ran too early — it must be ordered After=cloud-final.service."
  log "WARNING: The instance will work but is not labelled for a customer, and"
  log "WARNING: nginx will serve as a catch-all until banditdb-enable-tls sets"
  log "WARNING: the real server_name."
fi

if [[ -z "$CUSTOMER_ID" ]]; then
  CUSTOMER_ID="unnamed-$(head -c4 /dev/urandom | od -An -tx1 | tr -d ' \n')"
  log "no CUSTOMER_ID given, using $CUSTOMER_ID"
fi
[[ -n "$SERVER_NAME" ]] || SERVER_NAME="_"

log "provisioning customer=$CUSTOMER_ID host=$SERVER_NAME tier=$PLAN_TIER"

# ── Keys ─────────────────────────────────────────────────────────────────────
# Three roles. The customer normally uses the writer key in their application
# and never needs admin day to day.
ADMIN_KEY="bdb_admin_$(openssl rand -hex 24)"
WRITER_KEY="bdb_write_$(openssl rand -hex 24)"
READER_KEY="bdb_read_$(openssl rand -hex 24)"

# ── Server configuration ─────────────────────────────────────────────────────
umask 077
cat > "$ENV_FILE" <<EOF
# Generated by firstboot on $(date -u +%Y-%m-%dT%H:%M:%SZ) for $CUSTOMER_ID.
DATA_DIR=$DATA_DIR
PORT=8080
LOG_FORMAT=json
RUST_LOG=info

# Quoted deliberately. systemd's EnvironmentFile parser treats ';' as an
# ordinary character, so unquoted would work under systemd — but anyone who
# debugs by running 'source /etc/banditdb/banditdb.env' gets shell parsing,
# where ';' ends the statement and the value silently truncates after the first
# key. The result is a database where only the admin key works and the other two
# return 401, with nothing in the logs to explain it. Quoting is correct under
# both parsers.
BANDITDB_API_KEYS="$ADMIN_KEY=admin;$WRITER_KEY=writer;$READER_KEY=reader"
# Refuse to start rather than granting admin to everyone if the keys above are
# ever lost or mangled.
BANDITDB_REQUIRE_AUTH=true

# Dedicated instance: one customer, so no tenant prefixes needed.
BANDITDB_TENANT_MODE=false

# Empty denies all cross-origin requests. Set only if the customer calls the
# API from a browser, in which case their key is public anyway.
BANDITDB_CORS_ORIGINS=$CORS_ORIGINS

BANDITDB_CHECKPOINT_INTERVAL=5000
BANDITDB_MAX_WAL_SIZE_MB=100
BANDITDB_EXPORT_RETAIN_SHARDS=50

# The real memory bound. Pending predictions are ~1 KB each, and the TTL alone
# does not cap them: at 1,000 predictions/sec a 24h window would accumulate
# 86 million records. Raise both together for slow-converting outcomes.
BANDITDB_MAX_PENDING_INTERACTIONS=$MAX_PENDING
BANDITDB_REWARD_TTL_SECS=$REWARD_TTL_SECS

BANDITDB_RATE_LIMIT_PER_SEC=$RATE_LIMIT

# /metrics requires the reader key. Leave closed; scrape with the key.
BANDITDB_METRICS_PUBLIC=false
EOF
chown root:root "$ENV_FILE"; chmod 0600 "$ENV_FILE"

# ── nginx vhost ──────────────────────────────────────────────────────────────
sed "s/__SERVER_NAME__/$SERVER_NAME/g" \
  "$CONF_DIR/nginx-vhost.conf.template" > /etc/nginx/sites-available/banditdb
ln -sf /etc/nginx/sites-available/banditdb /etc/nginx/sites-enabled/banditdb
install -d -o www-data -g www-data /var/www/html
nginx -t
systemctl reload nginx

# ── Hostname ─────────────────────────────────────────────────────────────────
if [[ "$SERVER_NAME" != "_" ]]; then
  hostnamectl set-hostname "$(echo "$SERVER_NAME" | cut -d. -f1)" || true
fi

# ── Start ────────────────────────────────────────────────────────────────────
log "starting banditdb"
systemctl start banditdb

for _ in $(seq 1 30); do
  if curl -sf --max-time 2 http://127.0.0.1:8080/health >/dev/null 2>&1; then break; fi
  sleep 1
done

health="$(curl -sf --max-time 5 http://127.0.0.1:8080/health || echo '{}')"
version="$(echo "$health" | jq -r '.version // "unknown"' 2>/dev/null || echo unknown)"
features="$(echo "$health" | jq -c '.features // []' 2>/dev/null || echo '[]')"

if [[ "$version" == "unknown" ]]; then
  log "ERROR: BanditDB did not become healthy. journalctl -u banditdb"
  exit 1
fi
log "healthy: version=$version features=$features"

# ── Credentials, for the operator to collect and then delete ─────────────────
cat > "$CRED_FILE" <<EOF
BanditDB instance for: $CUSTOMER_ID
Provisioned:           $(date -u +%Y-%m-%dT%H:%M:%SZ)
Endpoint:              https://$SERVER_NAME
Version:               $version   features=$features

  admin   $ADMIN_KEY
  writer  $WRITER_KEY
  reader  $READER_KEY

Deliver these over a one-time secret link, never plain email.
Then: shred -u $CRED_FILE
EOF
chmod 0600 "$CRED_FILE"

cat <<EOF

  BanditDB is live for $CUSTOMER_ID on port 80.
  Credentials: $CRED_FILE

  Next:
    1. Point $SERVER_NAME at this instance's static IP
    2. sudo banditdb-enable-tls $SERVER_NAME <email>
    3. Run the durability check in deploy/lightsail/README.md
    4. Deliver credentials, then shred $CRED_FILE

EOF
